"""Remove foreign key constraint from Event.job_id for system events

Revision ID: 211b02203aa4
Revises: 6886e904fbad
Create Date: 2025-08-15 19:12:22.556136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211b02203aa4'
down_revision = '6886e904fbad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('event_job_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('event_job_id_fkey'), 'job', ['job_id'], ['id'])

    # ### end Alembic commands ###
