"""Add catalog store table

Revision ID: 666c1cd14871
Revises: 3a1f9d2b7e10
Create Date: 2025-08-14 20:51:53.718617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '666c1cd14871'
down_revision = '3a1f9d2b7e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_store',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalog_store')
    # ### end Alembic commands ###
