"""Make Event.job_id nullable for system-level events

Revision ID: 6886e904fbad
Revises: 666c1cd14871
Create Date: 2025-08-15 19:11:52.905323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6886e904fbad'
down_revision = '666c1cd14871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
