"""Initial migration

Revision ID: c55b0ceeb21b
Revises: 
Create Date: 2025-08-06 14:49:59.582838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c55b0ceeb21b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=False),
    sa.Column('student_email', sa.String(length=100), nullable=False),
    sa.Column('discipline', sa.String(length=50), nullable=False),
    sa.Column('class_number', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('metadata_path', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('printer', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=False),
    sa.Column('material', sa.String(length=32), nullable=False),
    sa.Column('weight_g', sa.Float(), nullable=True),
    sa.Column('time_hours', sa.Float(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('acknowledged_minimum_charge', sa.Boolean(), nullable=True),
    sa.Column('student_confirmed', sa.Boolean(), nullable=True),
    sa.Column('student_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirm_token', sa.String(length=128), nullable=True),
    sa.Column('confirm_token_expires', sa.DateTime(), nullable=True),
    sa.Column('is_confirmation_expired', sa.Boolean(), nullable=True),
    sa.Column('confirmation_last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('reject_reasons', sa.JSON(), nullable=True),
    sa.Column('staff_viewed_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('confirm_token')
    )
    op.create_table('staff',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('triggered_by', sa.String(length=100), nullable=False),
    sa.Column('workstation_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('txn_no', sa.String(length=50), nullable=False),
    sa.Column('picked_up_by', sa.String(length=100), nullable=False),
    sa.Column('paid_ts', sa.DateTime(), nullable=True),
    sa.Column('paid_by_staff', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('event')
    op.drop_table('staff')
    op.drop_table('job')
    # ### end Alembic commands ###
